### ISSUE TITLE
multiple vc

### ISSUE THREAD

**Issue by dapeng313** [PanMluvci/EMPageViewControllerMultiVCExample#1]
thanks for your repo.
I want multiple(at least 7vc)
can you provide example?

**Comment by PanMluvci** [comment]
I don't really understand why do u need another example. You will just add another VCs to storyboard and connect them to classes just like in example. Mission done. I think the example cannot be any more easy.

**Comment by PanMluvci** [comment]
another thing....if you want more than 2 VCs in example you have to rewrite this`    func em_pageViewController(_ pageViewController: EMPageViewController, viewControllerBeforeViewController viewController: UIViewController) -> UIViewController? {
        if selectedIndex == 0 && previousIndex != 1{
            previousIndex = selectedIndex
            selectedIndex = selectedIndex + 1
            return nil
        } else {
            return nil
        }
    }
    
    func em_pageViewController(_ pageViewController: EMPageViewController, viewControllerAfterViewController viewController: UIViewController) -> UIViewController? {
        if selectedIndex == 1 {
            previousIndex = selectedIndex
            selectedIndex = selectedIndex - 1
            return createSecondVC()
        } else {
            return nil
        }
    }`

**Comment by dapeng313** [comment]
Can we contact with meesenger?
